### ISSUE TITLE
v11 GFS changes in backup copy jobs

### ISSUE THREAD

**Issue by ZaphodJustSomeGuy** [tdewin/rps#18]
As outlined here:  https://www.veeam.com/blog/v11-gfs-retention.html Veeam have made a disruptive change to the way archive backups are processed.  Specifically not doing forever incremental anymore where the regular .VBK rolls up the the oldest .VIB once the restore points were reached (only with GFS switched on).

Does this mean there needs to be a change to the calc for backup copies (with v11+/GFS only)?

We missed this in the update notes and found out once our 2-restore point jobs with 1 monthly/yearly archives jumped from 4-5 restore points to 37, because it had to keep a whole month of incrementals between the monthly .VBKs after the upgrade.  The easy fix is just to add in at least 1 weekly archive (or not use GFS) to cut down the chain lengths.

**Comment by tdewin** [comment]
Yes the logic has indeed changed. A follow up project has been made but is waiting integration a bigger project allowing for doing a more complete sizing

**Comment by jstiops** [comment]
> Yes the logic has indeed changed. A follow up project has been made but is waiting integration a bigger project allowing for doing a more complete sizing

any news on the next gen sizer? :)

**Comment by dfillmore-mr** [comment]
We are also interested in status of this update.

**Comment by tdewin** [comment]
Hi, so this is not in my hands anymore. You can try the experimental sizing part here https://rps.dewin.me/rpc/
