### ISSUE TITLE
Incremental Backups with monthly active fulls

### ISSUE THREAD

**Issue by pmurray0** [tdewin/rps#3]
Hello!

I am looking for clarification (or perhaps error correction) in a specific scenario I've run into. 

Running a calculation using the RPS in a scenario with the following parameters: 

Incremental Backup
10TB
14 restore points
all else defaults
All 12 months selected for Active Full

(http://rps.dewin.me/?m=1&s=10000&r=14&c=50&d=10&i=D&dgr=10&dgy=1&dg=0&im=1,1,1,1,1,1,1,1,1,1,1,1&e)

Such a configuration results in a seemingly strange calculation in regards to restore point retention where the total retention is 48 points and the number of VIBs from first VBK to second is 35. Removing a month and re-running the calculation results in a marginal increase of points as well.

I'm trying to wrap my head around whether or not these monthly active full backups act in the same way as weekly active/synth fulls do and modify the chain, but even then the math doesn't seem to add up in my head. 

If this is indeed working as intended, would you mind explaining how the math works out? 

Thanks!

**Comment by tdewin** [comment]
Basically you are creating a huge dependency chain. You can see the (14) next to all the points. This means they are kept because they are needed to restore the 14th point. You can run the rps in manual mode to see what happens on a daily mode
