### ISSUE TITLE
Workspace function?

### ISSUE THREAD

**Issue by Pablomszen** [tdewin/rps#4]
Hi, first of all thanks for this resource, it's been very helpful.
I was wondering which function is used to calculate "workspace"? I'm trying to understand how it decreases   as the data from origin grows.
Thanks

**Comment by tdewin** [comment]
Here is a detailed explanation:
http://blog.dewin.me/2017/11/rps-workspace.html?m=1

Hope it helps

**Comment by Pablomszen** [comment]
Exactly hat i needed. Thanks!

*Pablo Medina Silva*

Consultor en Continuidad de Negocios





*Alfredo Barros Errázuriz 1953, Of. 305Providencia, Santiago de Chile+ 562
3224 3770+ 569 5009 5445www.rokka.cl <http://www.rokka.cl>*

[image: rokka-nous.png]

2017-12-29 6:32 GMT-03:00 tdewin <notifications@github.com>:

> Here is a detailed explanation:
> http://blog.dewin.me/2017/11/rps-workspace.html?m=1
>
> Hope it helps
>
