### ISSUE TITLE
Dedup

### ISSUE THREAD

**Issue by ArSo12** [tdewin/rps#6]
Hi,
Do you have any plans to include dedupe ratio?
I have a case where full backup in the incremental is taken with dedupe 2,5x while rest of incrementals is about 1,0x dedupe.

**Comment by tdewin** [comment]
Technically it could be done but i found that most people found it confusing (it is yet another field).

If you want smaller incrementals (2,5x) eg, just change the change rate by this factor (eg 10 to 5 or 4)
