### ISSUE TITLE
Time Growth Simulation breaks yearly rentention in BCJ

### ISSUE THREAD

**Issue by marcohorstmann** [tdewin/rps#7]
Hi Timo,

it seems that when you activate the Time Growth Simulation in Backup Copy Job Style
the yearly retention doesn't work anymore. Needs to be fixed.

**Comment by tdewin** [comment]
Could it be that you made a simulation for 1 year? Making a time simulation runs the simulation for today + x year you entered. if you have a high normal retention policy, you might not run into yearlies in that time frame

e.g
http://rps.dewin.me/?m=3&s=1000&r=14&c=50&d=10&i=D&dgr=10&dgy=1&dg=1&gaf=0&g=6,12,8,3&e

vs
http://rps.dewin.me/?m=3&s=1000&r=14&c=50&d=10&i=D&dgr=10&dgy=3&dg=1&gaf=0&g=6,12,8,3&e

**Comment by marcohorstmann** [comment]
Sorry for the delay. Yes this is correct. 3 years of retention but only 1 year growth simulation.
Problem is when someone using this for sizing and without noticing the 2nd and 3rd year of retention is not calculated in the space requirement he can run out of space. In my opinion it needs to be changed that even the growth simulation is only for a year calculation is needed for e.g. 3 years. Other option could be to override the no. of years in growth simulation and calculate it for the whole yearly retention points.

**Comment by tdewin** [comment]
At best I could make a warning message. But RPS simulates the time frame. If you simulate 1 year, you will get the result after one year :)

But yeah I could make a minimal time jump warning (e.g you have select 18 months of backup, consider 2 year simulation or something like that)

**Comment by tdewin** [comment]
annoying warning has been added ;)
